// RUN: circt-lec --emit-singular -c1 modA -c2 modB %s | FileCheck %s

hw.module @modA(in %a: i4, in %b: i4, out out: i4) {
  %0 = comb.and %a, %b : i4
  hw.output %0 : i4
}

hw.module @modB(in %a: i4, in %b: i4, out out: i4) {
  %0 = comb.and %a, %b : i4
  hw.output %0 : i4
}

// CHECK: // SCA equivalence proof generated by CIRCT
// CHECK: ring R = 0,
// CHECK: ideal I = J + B;
// CHECK: reduce(spec, std(I));
